GET http://localhost:3000/actors

###
GET http://localhost:3000/actors/5

###
POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Matt",
  "last_name": "Damon",
  "known_for": "The Bourne Identity"
}

###
PATCH http://localhost:3000/actors/16
Content-Type: application/json

{
  "first_name": "Matt",
  "last_name": "Damon",
  "known_for": "The Bourne Identity"
}

###
DELETE http://localhost:3000/actors/14

###
GET http://localhost:3000/movies/3

###
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Idiocracy",
  "year": 2006,
  "plot": "A guy of average intelligence wakes up in the future and society has become so dumb that he is considered a genius",
  "director": "Mike Judge"
}

###
PATCH http://localhost:3000/movies/8
Content-Type: application/json

{
  "title": "Dumb and Dumber",
  "year": 1994,
  "plot": "Two idiots go on a road trip to return a lost briefcase to a woman",
  "director": "Peter Farrelly",
  "english": true
}

###
DELETE http://localhost:3000/movies/6
